language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
before_script: 
-chmod +x ./build/scripts/setup_credentials.sh
-chmod +x ./build/scripts/deploy.sh
script: ./build/scripts/setup_credentials.sh
&& ./build/scripts/deploy.sh