language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
before_script: 
- chmod +x ./build/scripts/setup_credentials.sh
script: 
- ./build/scripts/setup_credentials.sh
- chmod +x ./build/scripts/deploy.sh
- chmod +x ./build/solenopsis/scripts/bsolenopsis
- chmod +x ./build/scripts/run_tests.sh
- ./build/scripts/deploy.sh