language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
before_script: chmod ugo+x ./src/build/scripts/setup_credentials.sh
script: chmod ugo+x ./src/build/scripts/deploy.sh